In [10]:
import torch

Question-2

In [11]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])

#3

In [12]:
tensor1 = torch.rand(1,7)
tensor2 = torch.transpose(tensor1,0,1) # transpose

print(tensor1)
print(tensor2)
torch.matmul(tensor1, tensor2) # matrix multiplication

tensor([[0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117]])
tensor([[0.3227],
        [0.0162],
        [0.2137],
        [0.6249],
        [0.4340],
        [0.1371],
        [0.5117]])


tensor([[1.0096]])

#4.1

In [13]:
RANDOM_SEED = 42
torch.rand(7,7)

tensor([[0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998, 0.5944],
        [0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600, 0.2846],
        [0.2007, 0.5014, 0.3139, 0.4654, 0.1612, 0.1568, 0.2083],
        [0.3289, 0.1054, 0.9192, 0.4008, 0.9302, 0.6558, 0.0766],
        [0.8460, 0.3624, 0.3083, 0.0850, 0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712, 0.1330, 0.4137, 0.6044, 0.7581],
        [0.9037, 0.9555, 0.1035, 0.6258, 0.2849, 0.4452, 0.1258]])

#4.2

In [14]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(1,7)

torch.manual_seed(RANDOM_SEED)
tensor2= torch.transpose(tensor1,0,1)

torch.matmul(tensor1, tensor2)

tensor([[3.2618]])

#10

In [16]:
RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(1,1,1,10)

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.squeeze(tensor1)

print(f'tensor1 matrix: {tensor1}')
print(f'tensor1 shape: {tensor1.shape}')
print(f'tensor2 matrix: {tensor2}')
print(f'tensor2 shape: {tensor2.shape}')



tensor1 matrix: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor1 shape: torch.Size([1, 1, 1, 10])
tensor2 matrix: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
tensor2 shape: torch.Size([10])
