In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.0.1


In [3]:
# `torch.tensor` is a multi-dimensional matrix containing elements of a single data type in PyTorch. 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim  # number of dimensions(ndim) of a tensor

0

In [5]:
scalar.item() # tensor back as python list

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
Matrix.ndim

2

In [11]:
Matrix[0]

tensor([1, 2])

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [17]:
random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.4223, 0.3994, 0.5052, 0.7149],
        [0.3702, 0.9575, 0.0237, 0.1529],
        [0.7546, 0.5609, 0.3340, 0.8738]])

In [18]:
random_tensor.ndim

2

In [19]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones Tensors

In [20]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
zeros.dtype

torch.float32

In [24]:
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data Types errors
1. Tesors not right datatypes- datatype==> tensor.dtype
2. Tensors not right shape - shape ==> tensor.shape
3. Tensors not on the right device - device ==> tensor.device

# Tensor Datatypes

In [41]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None # float32,float64,int32,int64
                               ,device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [44]:
float_32_tensor * float_16_tensor,(float_32_tensor * float_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [45]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long) # long = int32
int_32_tensor

tensor([3, 6, 9])

In [46]:
float_16_tensor*int_32_tensor,float_32_tensor*int_32_tensor

(tensor([ 9., 36., 81.], dtype=torch.float16), tensor([ 9., 36., 81.]))

# Tensor Attributes

In [51]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5225, 0.0380, 0.1435, 0.3523],
        [0.5333, 0.7059, 0.2554, 0.3314],
        [0.8723, 0.0724, 0.5915, 0.7029]])

In [53]:
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Size of the tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5225, 0.0380, 0.1435, 0.3523],
        [0.5333, 0.7059, 0.2554, 0.3314],
        [0.8723, 0.0724, 0.5915, 0.7029]])
DataType of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Size of the tensor: <built-in method size of Tensor object at 0x178d21b30>
Device tensor is on cpu


# Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [62]:
tensor = torch.tensor([1,2,3])
tensor+ 1000

tensor([1001, 1002, 1003])

In [63]:
tensor * 100

tensor([100, 200, 300])

In [65]:
tensor - 100

tensor([-99, -98, -97])

In [70]:
tensor

tensor([1, 2, 3])

In [73]:
# PyTorch inbuilt functions
torch.mul(tensor,100)

tensor([100, 200, 300])

In [74]:
torch.add(tensor,100)

tensor([101, 102, 103])

#  Rules of Matrix Multiplication (Dot product)

1. The **inner dimensions** must match:
* "(3,2) @ (3,2)" won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The Resulting matrix has the shape of the **outer dimesions**:
* '(2,3) @ (3,2)' - '(2,2)'
* '(3,2) @ (2,3)' - '(3,3)'


In [92]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.4715, 0.2681],
        [0.5408, 0.4006]])

In [76]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [77]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [90]:
tensor@tensor # we can use both matmul or @ operator 'better to use matmul'

tensor(14)

In [79]:
# Matrix Multiplication by Hand
1*1 + 2*2 + 3*3

14

In [87]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 811 µs, sys: 618 µs, total: 1.43 ms
Wall time: 1.02 ms


In [88]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 109 µs, sys: 33 µs, total: 142 µs
Wall time: 167 µs


tensor(14)

# Shape Errors

In [93]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose** switches the axes or dimensions of a given tensor

In [102]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [101]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [100]:
# Matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B}")
print(f"New shapes: tensor_A = {tensor_A}, tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
New shapes: tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
