In [96]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.0.1


In [97]:
# `torch.tensor` is a multi-dimensional matrix containing elements of a single data type in PyTorch. 
scalar = torch.tensor(7)
scalar

tensor(7)

In [98]:
scalar.ndim  # number of dimensions(ndim) of a tensor

0

In [99]:
scalar.item() # tensor back as python list

7

In [100]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [101]:
vector.ndim

1

In [102]:
vector.shape

torch.Size([2])

In [103]:
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [104]:
Matrix.ndim

2

In [105]:
Matrix[0]

tensor([1, 2])

In [106]:
Matrix.shape

torch.Size([2, 2])

In [107]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [108]:
Tensor.ndim

3

In [109]:
Tensor.shape

torch.Size([1, 3, 3])

In [110]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [111]:
random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.1640, 0.7152, 0.9805, 0.7940],
        [0.3970, 0.0136, 0.9735, 0.2463],
        [0.3565, 0.1108, 0.9330, 0.1998]])

In [112]:
random_tensor.ndim

2

In [113]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones Tensors

In [114]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [115]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [116]:
ones.dtype

torch.float32

In [117]:
zeros.dtype

torch.float32

In [118]:
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data Types errors
1. Tesors not right datatypes- datatype==> tensor.dtype
2. Tensors not right shape - shape ==> tensor.shape
3. Tensors not on the right device - device ==> tensor.device

# Tensor Datatypes

In [120]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None # float32,float64,int32,int64
                               ,device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [121]:
float_32_tensor.dtype

torch.float32

In [122]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [123]:
float_32_tensor * float_16_tensor,(float_32_tensor * float_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [124]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long) # long = int32
int_32_tensor

tensor([3, 6, 9])

In [125]:
float_16_tensor*int_32_tensor,float_32_tensor*int_32_tensor

(tensor([ 9., 36., 81.], dtype=torch.float16), tensor([ 9., 36., 81.]))

# Tensor Attributes

In [126]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7488, 0.7329, 0.2942, 0.7986],
        [0.2339, 0.1329, 0.8224, 0.1640],
        [0.5353, 0.3080, 0.0528, 0.1659]])

In [127]:
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Size of the tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7488, 0.7329, 0.2942, 0.7986],
        [0.2339, 0.1329, 0.8224, 0.1640],
        [0.5353, 0.3080, 0.0528, 0.1659]])
DataType of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Size of the tensor: <built-in method size of Tensor object at 0x16a832080>
Device tensor is on: cpu


# Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [128]:
tensor = torch.tensor([1,2,3])
tensor+ 1000

tensor([1001, 1002, 1003])

In [129]:
tensor * 100

tensor([100, 200, 300])

In [130]:
tensor - 100

tensor([-99, -98, -97])

In [131]:
tensor

tensor([1, 2, 3])

In [132]:
# PyTorch inbuilt functions
torch.mul(tensor,100)

tensor([100, 200, 300])

In [133]:
torch.add(tensor,100)

tensor([101, 102, 103])

#  Rules of Matrix Multiplication (Dot product)

1. The **inner dimensions** must match:
* "(3,2) @ (3,2)" won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The Resulting matrix has the shape of the **outer dimesions**:
* '(2,3) @ (3,2)' - '(2,2)'
* '(3,2) @ (2,3)' - '(3,3)'


In [134]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6055, 0.2249],
        [0.7203, 0.7710]])

In [135]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [136]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [137]:
tensor@tensor # we can use both matmul or @ operator 'better to use matmul'

tensor(14)

In [138]:
# Matrix Multiplication by Hand
1*1 + 2*2 + 3*3

14

In [139]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 508 µs, sys: 484 µs, total: 992 µs
Wall time: 623 µs


In [140]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 50 µs, sys: 14 µs, total: 64 µs
Wall time: 57 µs


tensor(14)

# Shape Errors

In [141]:
# # shapes for matrix multiplication
# tensor_A = torch.tensor([[1,2],
#                          [3,4],
#                          [5,6]])
# tensor_B = torch.tensor([[7,10],
#                          [8,11],
#                          [9,12]])

# torch.matmul(tensor_A,tensor_B)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose** switches the axes or dimensions of a given tensor

In [142]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [143]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [144]:
# Matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B}")
print(f"New shapes: tensor_A = {tensor_A}, tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
New shapes: tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean sum, etc (tensor aggregations)

In [147]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [149]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [150]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [153]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [155]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional maximum and minimum

In [156]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [160]:
# return the smallest value index position among the tensors
x.argmin()

tensor(0)

In [161]:
x[0]

tensor(0)

In [162]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permutes(swapped) in a certain way

In [163]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [168]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [169]:
# Changing the view 
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [170]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [171]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [172]:
x_reshaped.shape

torch.Size([1, 9])

In [177]:
# x_reshaped.squeeze()
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New Shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze(x) - adds a single dimension to a target tensor at a specific dimension
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

x_unsqueezed = x_squeezed.un

In [175]:
x_reshaped.squeeze().shape

torch.Size([9])