In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.0.1


In [5]:
# `torch.tensor` is a multi-dimensional matrix containing elements of a single data type in PyTorch. 
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim  # number of dimensions(ndim) of a tensor

0

In [7]:
scalar.item() # tensor back as python list

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [14]:
Matrix.ndim

2

In [15]:
Matrix[0]

tensor([1, 2])

In [16]:
Matrix.shape

torch.Size([2, 2])

In [21]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
Tensor.ndim

3

In [23]:
Tensor.shape

torch.Size([1, 3, 3])

In [24]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [26]:
random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.7746, 0.2797, 0.1415, 0.3669],
        [0.9936, 0.7572, 0.5611, 0.2740],
        [0.3379, 0.0938, 0.7995, 0.1766]])

In [27]:
random_tensor.ndim

2

In [32]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones Tensors

In [40]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [45]:
zeros.dtype

torch.float32

In [51]:
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [55]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [56]:
float_32_tensor.dtype

torch.float16