In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.0.1


In [5]:
# `torch.tensor` is a multi-dimensional matrix containing elements of a single data type in PyTorch. 
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim  # number of dimensions(ndim) of a tensor

0

In [7]:
scalar.item() # tensor back as python list

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [14]:
Matrix.ndim

2

In [15]:
Matrix[0]

tensor([1, 2])

In [16]:
Matrix.shape

torch.Size([2, 2])

In [21]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
Tensor.ndim

3

In [23]:
Tensor.shape

torch.Size([1, 3, 3])

In [24]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])