In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.0.1


In [95]:
# `torch.tensor` is a multi-dimensional matrix containing elements of a single data type in PyTorch. 
scalar = torch.tensor(7)
scalar

tensor(7)

In [96]:
scalar.ndim  # number of dimensions(ndim) of a tensor

0

In [97]:
scalar.item() # tensor back as python list

7

In [98]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [99]:
vector.ndim

1

In [100]:
vector.shape

torch.Size([2])

In [101]:
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [102]:
Matrix.ndim

2

In [103]:
Matrix[0]

tensor([1, 2])

In [104]:
Matrix.shape

torch.Size([2, 2])

In [105]:
Tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [106]:
Tensor.ndim

3

In [107]:
Tensor.shape

torch.Size([1, 3, 3])

In [108]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [109]:
random_tensor = torch.rand(3,4)
random_tensor 

tensor([[0.1224, 0.9323, 0.4788, 0.3986],
        [0.1884, 0.4206, 0.5760, 0.2005],
        [0.7744, 0.6233, 0.2373, 0.9033]])

In [110]:
random_tensor.ndim

2

In [111]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones Tensors

In [112]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
ones.dtype

torch.float32

In [115]:
zeros.dtype

torch.float32

In [116]:
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data Types errors
1. Tesors not right datatypes- datatype==> tensor.dtype
2. Tensors not right shape - shape ==> tensor.shape
3. Tensors not on the right device - device ==> tensor.device

# Tensor Datatypes

In [118]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None # float32,float64,int32,int64
                               ,device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [119]:
float_32_tensor.dtype

torch.float32

In [120]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [121]:
float_32_tensor * float_16_tensor,(float_32_tensor * float_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [122]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long) # long = int32
int_32_tensor

tensor([3, 6, 9])

In [123]:
float_16_tensor*int_32_tensor,float_32_tensor*int_32_tensor

(tensor([ 9., 36., 81.], dtype=torch.float16), tensor([ 9., 36., 81.]))

# Tensor Attributes

In [124]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9468, 0.3120, 0.1089, 0.6226],
        [0.1082, 0.5348, 0.3437, 0.2335],
        [0.6154, 0.8541, 0.7370, 0.7160]])

In [125]:
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Size of the tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9468, 0.3120, 0.1089, 0.6226],
        [0.1082, 0.5348, 0.3437, 0.2335],
        [0.6154, 0.8541, 0.7370, 0.7160]])
DataType of tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Size of the tensor: <built-in method size of Tensor object at 0x17a846850>
Device tensor is on: cpu


# Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [126]:
tensor = torch.tensor([1,2,3])
tensor+ 1000

tensor([1001, 1002, 1003])

In [127]:
tensor * 100

tensor([100, 200, 300])

In [128]:
tensor - 100

tensor([-99, -98, -97])

In [129]:
tensor

tensor([1, 2, 3])

In [130]:
# PyTorch inbuilt functions
torch.mul(tensor,100)

tensor([100, 200, 300])

In [131]:
torch.add(tensor,100)

tensor([101, 102, 103])

#  Rules of Matrix Multiplication (Dot product)

1. The **inner dimensions** must match:
* "(3,2) @ (3,2)" won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The Resulting matrix has the shape of the **outer dimesions**:
* '(2,3) @ (3,2)' - '(2,2)'
* '(3,2) @ (2,3)' - '(3,3)'


In [132]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.4739, 0.6649],
        [1.1156, 1.4923]])

In [133]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [134]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [135]:
tensor@tensor # we can use both matmul or @ operator 'better to use matmul'

tensor(14)

In [136]:
# Matrix Multiplication by Hand
1*1 + 2*2 + 3*3

14

In [137]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 472 µs, sys: 542 µs, total: 1.01 ms
Wall time: 583 µs


In [138]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 23 µs, sys: 2 µs, total: 25 µs
Wall time: 26 µs


tensor(14)

# Shape Errors

In [139]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.matmul(tensor_A,tensor_B)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose** switches the axes or dimensions of a given tensor

In [140]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [141]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [142]:
# Matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B}")
print(f"New shapes: tensor_A = {tensor_A}, tensor_B.T = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
New shapes: tensor_A = tensor([[1, 2],
        [3, 4],
        [5, 6]]), tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean sum, etc (tensor aggregations)

In [143]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [144]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [145]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [146]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [147]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional maximum and minimum

In [148]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [149]:
# return the smallest value index position among the tensors
x.argmin()

tensor(0)

In [150]:
x[0]

tensor(0)

In [151]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permutes(swapped) in a certain way

In [152]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
# Changing the view 
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [156]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [157]:
x_reshaped.shape

torch.Size([1, 9])

In [158]:
# x_reshaped.squeeze()
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New Shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [163]:
# torch.unsqueeze(x) - adds a single dimension to a target tensor at a specific dimension
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [165]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

x_permute = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f'New shape: {x_permute.shape}') #[color_channels,width,height]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [166]:
x_original[0,0,0] = 728218
x_original[0,0,0],x_permute[0,0,0]

(tensor(728218.), tensor(728218.))

# Indexing( selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [168]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [169]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [171]:
# index on middle bracket dim = 1
x[0][0]

tensor([1, 2, 3])

In [172]:
# index on the inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [173]:
# to get 9
x[0][2][2]

tensor(9)

In [174]:
# ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [176]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [177]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [178]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [181]:
# Index on X to return 9
x[0,2,2]
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library. And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch in tensor --> 'torch.from_numpy(ndarray)
* PyTorch tensor --> NumPy --> 'torch.Tensor.numpy()

In [184]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # gives default datatype
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [185]:
array.dtype

dtype('float64')

In [186]:
tensor.dtype

torch.float64

In [187]:
# Change the value of the array
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [188]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [189]:
# Change th tensor
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (random out of random)

'start with random number --> tensor operations --> update random numbers to try and make them better representations of the data--> again -- again'

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is 'flavour' the randomness

In [192]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6106, 0.6978, 0.7463, 0.5855],
        [0.9637, 0.5077, 0.1303, 0.0839],
        [0.1392, 0.4722, 0.2072, 0.5413]])
tensor([[0.1481, 0.0485, 0.7045, 0.0300],
        [0.9393, 0.0806, 0.4967, 0.8371],
        [0.7253, 0.1944, 0.4766, 0.1518]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [194]:
# random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [196]:
torch.cuda.is_available()

False

In [ ]:
# complete excersices for answers refer github